[package]
name = "my-rust-module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gloo = "0.8.1"
js-sys = "0.3.77"
wasm-bindgen-futures = "0.4.50"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
wasm-bindgen-test = "0.3.50"
